### PR TITLE
Fix for using EC2 IAM credentials for S3 access

### LINKED ISSUE #44: S3 object store on aws should not require credentials
accesskey and secretkey should not be required as aws-sdk when running on an AWS instance will pull the credentials from the metadata service

### PR DESCRIPTION
**Pull request by ApsOps**
- Continue without AWS env vars if the config doesn't exist
- Possibly fixes #44 and #88

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by mboersma** [comment]
Jenkins, add to whitelist.

**Comment by vdice** [comment]
This certainly seems like a reasonable fix to me, LGTM; ping @bacongobbler @mboersma

File: main.go [hunk 1]
```diff
@@ -37,14 +37,18 @@ func main() {
 			log.Fatal(err)
 		} else {
 			os.Setenv("REGISTRY_STORAGE_S3_ACCESSKEY", string(accesskey))
```
Comment (bacongobbler) [inline main.go:39]: I have a feeling that while everything below will work, object-storage-cli will not pick up on IAM credentials due to the reliance on REGISTRY_STORAGE_S3_ACCESSKEY. The previous maintainer is long gone so I don't have a solid reason why we decided to use this envvar name. Have you tested this PR and registry blobs are being uploaded to S3 as expected?

Comment (ApsOps) [reply main.go:39]: @bacongobbler yeah, it's working for us. I think this change is required only for use by boto 2.

**Review by mboersma — APPROVED** [review]
